# Generated by Django 4.2 on 2025-07-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_alter_profile_image_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
